name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.5.2
      with:
          ssh-private-key: ${{ secrets.PRIVKEY }}
    - name: Deploy
      run: bash .github/workflows/deploy.sh
      
